import { FileType } from '../../file-types';
import { isNully } from '../../../null';
import { safeGet } from '../../../array';

export const catBaseBalls = [
  'ankleL',
  'ankleR',
  'belly',
  'butt',
  'cheekL',
  'cheekR',
  'chest',
  'chin',
  'earL1',
  'earL2',
  'earR1',
  'earR2',
  'elbowL',
  'elbowR',
  'eyeL',
  'eyeR',
  'fingerL1',
  'fingerL2',
  'fingerL3',
  'fingerR1',
  'fingerR2',
  'fingerR3',
  'handL',
  'handR',
  'head',
  'hipL',
  'hipR',
  'irisL',
  'irisR',
  'jaw',
  'jowlL',
  'jowlR',
  'kneeL',
  'kneeR',
  'knuckleL',
  'knuckleR',
  'neck',
  'nose',
  'shoulderL',
  'shoulderR',
  'snout',
  'soleL(i.e.thefoot)',
  'soleR(i.e.thefoot)',
  'tail1(nearesttothebutt)',
  'tail2',
  'tail3',
  'tail4',
  'tail5',
  'tail6(tip)',
  'toeL1',
  'toeL2',
  'toeL3',
  'toeR1',
  'toeR2',
  'toeR3',
  'tongue1',
  'tongue2',
  'whiskerL1',
  'whiskerL2',
  'whiskerL3',
  'whiskerR1',
  'whiskerR2',
  'whiskerR3',
  'wristL',
  'wristR',
  'zorient',
  'ztrans',
];

export const dogBaseBalls = [
  'Lankle',
  'Leyebrow1',
  'Leyebrow2',
  'Leyebrow3',
  'Lear1',
  'Lear2',
  'Lear3',
  'Lelbow',
  'Leye',
  'Lfinger1',
  'Lfinger2',
  'Lfinger3',
  'Lfoot',
  'Lhand',
  'Liris',
  'Ljowl',
  'Lknee',
  'Lnostril',
  'Lshoulder',
  'Lhip',
  'Ltoe1',
  'Ltoe2',
  'Ltoe3',
  'Lwrist',
  'Rankle',
  'Reyebrow1',
  'Reyebrow2',
  'Reyebrow3',
  'Rear1',
  'Rear2',
  'Rear3',
  'Relbow',
  'Reye',
  'Rfinger1',
  'Rfinger2',
  'Rfinger3',
  'Rfoot',
  'Rhand',
  'Riris',
  'Rjowl',
  'Rknee',
  'Rnostril',
  'Rshoulder',
  'Rhip',
  'Rtoe1',
  'Rtoe2',
  'Rtoe3',
  'Rwrist',
  'Belly',
  'Butt',
  'Chest',
  'Chin',
  'Head',
  'Jaw',
  'Neck',
  'Nose(bottom)',
  'Snout',
  'Tail1',
  'Tail2',
  'Tail3',
  'Tail4',
  'Tail5',
  'Tail6',
  'Tongue1',
  'Tongue2',
  'Z-trans',
  'Z-orient',
];

export const ballLabels: Record<FileType, string[] | null> = {
  catz: catBaseBalls,
  dogz: dogBaseBalls,
  clothes: null,
};

const catBaseBallsAbbr = [
  'ankL',
  'ankR',
  'bely',
  'butt',
  'chkL',
  'chkR',
  'chst',
  'chin',
  'erL1',
  'erL2',
  'erR1',
  'erR2',
  'elbL',
  'elbR',
  'eyeL',
  'eyeR',
  'fnL1',
  'fnL2',
  'fnL3',
  'fnR1',
  'fnR2',
  'fnR3',
  'hndL',
  'hndR',
  'head',
  'hipL',
  'hipR',
  'irsL',
  'irsR',
  'jaw',
  'jwlL',
  'jwlR',
  'neeL',
  'neeR',
  'nucL',
  'nucR',
  'neck',
  'nose',
  'shlL',
  'shlR',
  'snut',
  'solL',
  'solR',
  'tai1',
  'tai2',
  'tai3',
  'tai4',
  'tai5',
  'tal6',
  'toL1',
  'toL2',
  'toL3',
  'toR1',
  'toR2',
  'toR3',
  'tng1',
  'tng2',
  'wsL1',
  'wsL2',
  'wsL3',
  'wsR1',
  'wsR2',
  'wsR3',
  'rstL',
  'rstR',
  'zort',
  'ztrn',
] as const;
export type CatBallAbbr = (typeof catBaseBallsAbbr)[number];
const dogBaseBallsAbbr = [
  'ankL',
  'br1L',
  'br2L',
  'br3L',
  'er1L',
  'er2L',
  'er3L',
  'elbL',
  'eyeL',
  'fn1L',
  'fn2L',
  'fn3L',
  'ftL',
  'hndL',
  'irsL',
  'jwlL',
  'neeL',
  'nstL',
  'shlL',
  'hipL',
  'to1L',
  'to2L',
  'to3L',
  'rstL',
  'ankR',
  'br1R',
  'br2R',
  'br3R',
  'er1R',
  'er2R',
  'er3R',
  'elbR',
  'eyeR',
  'fn1R',
  'fn2R',
  'fn3R',
  'ftR',
  'hndR',
  'irsR',
  'jwlR',
  'neeR',
  'nstR',
  'shlR',
  'hipR',
  'to1R',
  'to2R',
  'to3R',
  'rstR',
  'bely',
  'butt',
  'chst',
  'chin',
  'head',
  'jaw',
  'neck',
  'nose',
  'snut',
  'tai1',
  'tai2',
  'tai3',
  'tai4',
  'tai5',
  'tai6',
  'tng1',
  'tng2',
  'ztrn',
  'zort',
] as const;
export type DogBallAbbr = (typeof dogBaseBallsAbbr)[number];

const bodyZones = [
  'head',
  'body',
  'frontLegs',
  'backLegs',
  'tail',
  'misc',
] as const;

export type BodyZone = (typeof bodyZones)[number];

export const catBallToZone: Record<CatBallAbbr, BodyZone> = {
  ankL: 'backLegs',
  ankR: 'backLegs',
  bely: 'body',
  butt: 'body',
  chkL: 'head',
  chkR: 'head',
  chst: 'body',
  chin: 'head',
  erL1: 'head',
  erL2: 'head',
  erR1: 'head',
  erR2: 'head',
  elbL: 'frontLegs',
  elbR: 'frontLegs',
  eyeL: 'head',
  eyeR: 'head',
  fnL1: 'frontLegs',
  fnL2: 'frontLegs',
  fnL3: 'frontLegs',
  fnR1: 'frontLegs',
  fnR2: 'frontLegs',
  fnR3: 'frontLegs',
  hndL: 'frontLegs',
  hndR: 'frontLegs',
  head: 'head',
  hipL: 'backLegs',
  hipR: 'backLegs',
  irsL: 'head',
  irsR: 'head',
  jaw: 'head',
  jwlL: 'head',
  jwlR: 'head',
  neeL: 'backLegs',
  neeR: 'backLegs',
  nucL: 'backLegs',
  nucR: 'backLegs',
  neck: 'body',
  nose: 'head',
  shlL: 'frontLegs',
  shlR: 'frontLegs',
  snut: 'head',
  solL: 'backLegs',
  solR: 'backLegs',
  tai1: 'tail',
  tai2: 'tail',
  tai3: 'tail',
  tai4: 'tail',
  tai5: 'tail',
  tal6: 'tail',
  toL1: 'backLegs',
  toL2: 'backLegs',
  toL3: 'backLegs',
  toR1: 'backLegs',
  toR2: 'backLegs',
  toR3: 'backLegs',
  tng1: 'head',
  tng2: 'head',
  wsL1: 'head',
  wsL2: 'head',
  wsL3: 'head',
  wsR1: 'head',
  wsR2: 'head',
  wsR3: 'head',
  rstL: 'frontLegs',
  rstR: 'frontLegs',
  zort: 'misc',
  ztrn: 'misc',
};

export const dogBallToZone: Record<DogBallAbbr, BodyZone> = {
  ankL: 'backLegs',
  br1L: 'head',
  br2L: 'head',
  br3L: 'head',
  er1L: 'head',
  er2L: 'head',
  er3L: 'head',
  elbL: 'frontLegs',
  eyeL: 'head',
  fn1L: 'frontLegs',
  fn2L: 'frontLegs',
  fn3L: 'frontLegs',
  ftL: 'backLegs',
  hndL: 'frontLegs',
  irsL: 'head',
  jwlL: 'head',
  neeL: 'backLegs',
  nstL: 'head',
  shlL: 'frontLegs',
  hipL: 'backLegs',
  to1L: 'backLegs',
  to2L: 'backLegs',
  to3L: 'backLegs',
  rstL: 'frontLegs',
  ankR: 'backLegs',
  br1R: 'head',
  br2R: 'head',
  br3R: 'head',
  er1R: 'head',
  er2R: 'head',
  er3R: 'head',
  elbR: 'frontLegs',
  eyeR: 'head',
  fn1R: 'frontLegs',
  fn2R: 'frontLegs',
  fn3R: 'frontLegs',
  ftR: 'backLegs',
  hndR: 'frontLegs',
  irsR: 'head',
  jwlR: 'head',
  neeR: 'backLegs',
  nstR: 'head',
  shlR: 'frontLegs',
  hipR: 'backLegs',
  to1R: 'backLegs',
  to2R: 'backLegs',
  to3R: 'backLegs',
  rstR: 'frontLegs',
  bely: 'body',
  butt: 'body',
  chst: 'body',
  chin: 'head',
  head: 'head',
  jaw: 'head',
  neck: 'body',
  nose: 'head',
  snut: 'head',
  tai1: 'tail',
  tai2: 'tail',
  tai3: 'tail',
  tai4: 'tail',
  tai5: 'tail',
  tai6: 'tail',
  tng1: 'head',
  tng2: 'head',
  ztrn: 'misc',
  zort: 'misc',
};

export const ballAbrsAndZones = {
  catz: {
    abbr: catBaseBallsAbbr,
    zones: catBallToZone,
  },
  dogz: {
    abbr: dogBaseBallsAbbr,
    zones: dogBallToZone,
  },
  clothes: null,
};

export interface BallLabelData {
  label: string;
  abbr: string;
  zone: BodyZone;
}

export function getBallLabelData<A extends FileType>(
  ballId: number,
  fileType: A
) {
  const abbrs = ballAbrsAndZones[fileType];
  const labels = ballLabels[fileType];
  if (isNully(abbrs) || isNully(labels)) return null;
  const label = safeGet(labels, ballId);
  if (isNully(label)) return null;
  const abbr = safeGet(abbrs.abbr, ballId);
  if (isNully(abbr)) return null;
  return {
    label,
    abbr,
    zone: (abbrs.zones as any)[abbr] as BodyZone,
  };
}
